name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build Application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test

      - name: Build Application
        run: npm run build

      - name: Archive Production Artifact
        uses: actions/upload-artifact@v3
        with:
          name: production-build
          path: ./.output/ # Adjust path based on your build output 

  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: production-build
          path: ./build

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Add VPS to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Transfer Build to VPS
        run: |
          rsync -avz --delete ./build/ ${ { secrets.VPS_USER } }@${ { secrets.VPS_HOST }}:/var/www/valedoise-rh/.output/

      - name: Deploy on VPS
        run: |
          ssh ${ { secrets.VPS_USER } }@${ { secrets.VPS_HOST }} "
            cd /var/www/valedoise-rh &&
            npm install --production &&
            pm2 reload ecosystem.config.js --env production
          "

      - name: Notify Deployment Success
        if: success()
        uses: some/notification-action@v1
        with:
          message: "Deployment to VPS was successful!"
          # Configure additional notification parameters

      - name: Notify Deployment Failure
        if: failure()
        uses: some/notification-action@v1
        with:
          message: "Deployment to VPS failed!"
          # Configure additional notification parameters
